# Generated by Django 5.2.16 on 2026-09-01 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(blank=True, choices=[('6m', '6 months before'), ('3m', '3 months before'), ('1m', '1 month before'), ('7d', '7 days before'), ('1d', '1 day before'), ('onExpiry', 'On expiry date')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=12)),
                ('reminder_date', models.DateField()),
                ('notification_method', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_date'],
                'constraints': [models.UniqueConstraint(fields=('document', 'preset', 'reminder_date', 'email'), name='unique_document_reminder')],
            },
        ),
    ]
