# Generated by Django 5.2.16 on 2026-09-01 13:34

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Passport', 'Passport'), ('Visa', 'Visa'), ('Emirates ID', 'Emirates ID'), ('Driving Licence', 'Driving Licence'), ('Insurance', 'Insurance'), ('Trade Licence', 'Trade Licence'), ('Vehicle Registration', 'Vehicle Registration'), ('Contract', 'Contract'), ('Other', 'Other')], max_length=64)),
                ('document_name', models.CharField(max_length=160)),
                ('holder_name', models.CharField(blank=True, max_length=160)),
                ('document_number', models.CharField(blank=True, max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('issuing_country', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=160)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_path)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('ai_confidence', models.PositiveSmallIntegerField(default=0)),
                ('user_verified', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', '-created_at'],
            },
        ),
    ]
